# Generated by Django 4.1.6 on 2023-05-31 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_ticketmodel_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingRegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_registration', to='main.ticketmodel')),
            ],
        ),
    ]
