version: '3'

services:
  web:
    build: django_air_erp_system
    command: gunicorn django_air_erp_system.wsgi --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_air_erp_system

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379

  worker:
    build: ./django_air_erp_system
    command: celery -A django_air_erp_system worker -l INFO
    volumes:
      - .:/code:Z
    env_file:
      - ./.env
    links:
        - redis
    depends_on:
        - redis
  nginx:
    image: nginx:1.23.4
    ports:
      - '8000:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
