# Generated by Django 4.1.6 on 2023-05-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FlightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_cancelled', models.BooleanField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.airplanemodel')),
            ],
            options={
                'ordering': ['start_location', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='OptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.flightmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='SeatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='main.airplanemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SeatTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('EC', 'Economy class'), ('PR', 'Premium economy class'), ('BU', 'Business class'), ('FI', 'First class')], default='EC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='main.flightmodel')),
                ('options', models.ManyToManyField(blank=True, to='main.optionmodel')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seatmodel')),
            ],
            options={
                'ordering': ['-flight'],
            },
        ),
        migrations.AddField(
            model_name='seatmodel',
            name='seat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seattypemodel'),
        ),
        migrations.AddField(
            model_name='optionmodel',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_prices', to='main.pricemodel'),
        ),
        migrations.CreateModel(
            name='LuggageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage_prices', to='main.pricemodel')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='luggage', to='main.ticketmodel')),
            ],
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_prices', to='main.pricemodel'),
        ),
        migrations.AddField(
            model_name='flightmodel',
            name='seats',
            field=models.ManyToManyField(to='main.seatmodel'),
        ),
    ]
